"""Pinned leaf compatibility and child-only redirect budget plumbing."""

import runpy
import socket
import threading
import time
from pathlib import Path

import pytest

from tests.test_outbound_ssrf_driver import _PassThroughTLS
from tests.test_outbound_ssrf_driver import stub_server as stub_server
from tinyassets.storage.outbound_connections import (
    SsrfValidationError,
    _execute_pinned_https_request,
    _HttpHopMetadata,
    _parse_canonical_https_url,
    _SsrfHardenedHttpDriver,
)


def _leaf_kwargs(server, **overrides):
    port = server.server_address[1]
    return {
        "method": "GET",
        "canonical": _parse_canonical_https_url(
            f"https://api.example.com:{port}/download",
            allowed_ports=frozenset({port}),
        ),
        "pinned_address": "127.0.0.1",
        "headers": {},
        "body": None,
        "ssl_context": _PassThroughTLS(),
        "open_socket": lambda address, timeout, source: socket.create_connection(address, timeout),
        "timeout": 2.0,
        "max_total_seconds": 2.0,
        "max_body_bytes": 1000,
        "max_header_count": 20,
        "max_header_bytes": 5000,
        **overrides,
    }


@pytest.fixture(scope="module")
def legacy_leaf():
    return runpy.run_path(
        str(Path(__file__).with_name("fixtures") / "legacy_download_transport.py")
    )["_execute_pinned_https_request"]


@pytest.mark.parametrize("status", [200, 301, 302, 303, 307, 308, 404])
@pytest.mark.parametrize("body", [b"download text", b"non-utf8\xff"])
def test_default_leaf_matches_frozen_no_follow_transport(stub_server, legacy_leaf, status, body):
    stub_server.stub.update(
        status=status,
        body=body,
        extra_headers=(
            ("Location", "https://first.example.com/a"),
            ("Location", "https://second.example.com/b"),
        ),
    )
    old = legacy_leaf(**_leaf_kwargs(stub_server))
    current = _execute_pinned_https_request(**_leaf_kwargs(stub_server))
    # Date is generated by the server and may cross a wall-clock second.
    old["headers"].pop("date", None)
    current["headers"].pop("date", None)
    assert current == old
    assert set(current) == {"status", "reason", "headers", "body"}


def test_leaf_retains_duplicate_locations_only_in_supplied_child_metadata(stub_server):
    locations = ("https://first.example.com/signed?token=one", "https://other.example.com/two")
    stub_server.stub.update(
        status=302,
        body=b"\xffdata",
        extra_headers=tuple(("Location", value) for value in locations),
    )
    metadata = _HttpHopMetadata()
    result = _execute_pinned_https_request(**_leaf_kwargs(stub_server), hop_metadata=metadata)
    assert metadata.locations == locations
    assert metadata.body_bytes == 5
    assert "signed" not in repr(metadata)
    assert set(result) == {"status", "reason", "headers", "body"}
    assert result["headers"]["location"] == locations[-1]  # legacy projection unchanged


def test_expired_shared_deadline_refuses_before_opening_a_socket(stub_server):
    calls = []
    with pytest.raises(SsrfValidationError, match="total deadline"):
        _execute_pinned_https_request(
            **_leaf_kwargs(
                stub_server,
                open_socket=lambda *args: calls.append(args),
            ),
            absolute_deadline=time.monotonic() - 1,
        )
    assert calls == []


def test_remaining_chain_budget_bounds_initial_dns():
    release = threading.Event()
    started = threading.Event()

    def resolver(host, port):
        started.set()
        release.wait(5)
        return ["8.8.8.8"]

    driver = _SsrfHardenedHttpDriver(resolver=resolver, dns_timeout=5)
    canonical = _parse_canonical_https_url("https://api.example.com/download", allowed_ports={443})
    beginning = time.monotonic()
    try:
        with pytest.raises(SsrfValidationError, match="deadline"):
            driver._redirect_address(canonical, beginning + 0.04)
        assert started.is_set()
        assert time.monotonic() - beginning < 1
    finally:
        release.set()  # abandoned resolver belongs to the child, never to caller state


def test_redirect_dns_still_validates_every_resolved_address():
    driver = _SsrfHardenedHttpDriver(resolver=lambda host, port: ["8.8.8.8", "127.0.0.1"])
    canonical = _parse_canonical_https_url("https://api.example.com/download", allowed_ports={443})
    with pytest.raises(SsrfValidationError):
        driver._redirect_address(canonical, time.monotonic() + 2)


@pytest.mark.parametrize(
    "limits",
    [
        {"max_body_bytes": 2},
        {"max_header_count": 1},
        {"max_header_bytes": 2},
    ],
)
def test_default_leaf_bound_refusals_match_frozen_transport(stub_server, legacy_leaf, limits):
    stub_server.stub.update(body=b"larger response")
    errors = []
    for execute in (legacy_leaf, _execute_pinned_https_request):
        with pytest.raises(SsrfValidationError) as caught:
            execute(**_leaf_kwargs(stub_server, **limits))
        errors.append((type(caught.value), str(caught.value)))
    assert errors[0] == errors[1]


def test_leaf_honors_remaining_deadline_instead_of_starting_a_new_budget(stub_server):
    def slow_open(address, timeout, source):
        time.sleep(0.08)
        return socket.create_connection(address, timeout)

    with pytest.raises(SsrfValidationError, match="total deadline"):
        _execute_pinned_https_request(
            **_leaf_kwargs(
                stub_server,
                open_socket=slow_open,
                max_total_seconds=10,
            ),
            absolute_deadline=time.monotonic() + 0.04,
        )
