"""PR-122 Phase 2 Slice 1 — three-gate authority for the GitHub PR effector.

Covers:
  - Each gate failure case independently:
      * no destination on packet -> Phase 1 backward-compat dry-run
      * destination + missing capability env -> Phase 2 dry-run
      * destination + capability + missing consent grant -> Phase 2 dry-run
      * idempotency receipt already present -> dedup hit, no subprocess
  - Happy path with all three gates open -> real subprocess invocation +
    receipt recorded
  - Concurrent retries with the same idempotency_hint -> second call
    returns dedup hit without re-invoking gh
  - Capability env-key derivation for multiple destinations
  - Subprocess is fully mocked; no test touches real GitHub
  - Failure paths (gh exit nonzero / missing / timeout / no-URL-in-stdout)
    do NOT record receipts
"""

from __future__ import annotations

import json
import subprocess
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from workflow.branches import NodeDefinition
from workflow.effectors import EXTERNAL_WRITE_SINK_GITHUB_PR
from workflow.effectors.github_pr import (
    _capability_env_key,
    run_effects_for_branch,
    run_github_pr_effector,
)
from workflow.storage.effector_consents import grant_consent
from workflow.storage.external_write_receipts import (
    lookup_receipt,
    record_receipt,
)

_DESTINATION = "Jonnyton/Workflow"
_CAPABILITY_ENV = "WORKFLOW_GITHUB_PR_CAPABILITY_REPO_JONNYTON_WORKFLOW"
_HEAD_BRANCH = "auto/loop-2/cycle-001"


def _make_packet(
    *,
    destination: str | None = _DESTINATION,
    idempotency_hint: str | None = "loop-2-cycle-001",
    head_branch: str = _HEAD_BRANCH,
    title: str = "Loop 2 cycle 001: fix BUG-049",
) -> dict:
    packet = {
        "sink": EXTERNAL_WRITE_SINK_GITHUB_PR,
        "payload": {
            "title": title,
            "body": "Generated by Loop 2 workflow run.",
            "base_branch": "main",
            "head_branch": head_branch,
            "labels": ["writer:loop-2"],
            "draft": True,
        },
        "expected_evidence_keys": ["pr_number", "pr_url"],
    }
    if destination is not None:
        packet["destination"] = destination
    if idempotency_hint is not None:
        packet["idempotency_hint"] = idempotency_hint
    return packet


@pytest.fixture
def universe_dir(tmp_path):
    """Per-test universe directory the effector can use for the storage gates."""
    universe = tmp_path / "u-test"
    universe.mkdir()
    return universe


@pytest.fixture(autouse=True)
def _clean_capability_env(monkeypatch):
    """Strip any capability env vars the host shell may have set."""
    for name in list(__import__("os").environ.keys()):
        if name.startswith("WORKFLOW_GITHUB_PR_CAPABILITY_REPO_"):
            monkeypatch.delenv(name, raising=False)
    monkeypatch.delenv("WORKFLOW_EXTERNAL_WRITE_ENABLED", raising=False)
    monkeypatch.delenv("WORKFLOW_EXTERNAL_WRITE_DRY_RUN", raising=False)


# ---------------------------------------------------------------------------
# Capability env-key derivation
# ---------------------------------------------------------------------------


def test_capability_env_key_for_simple_destination():
    assert _capability_env_key("Jonnyton/Workflow") == (
        "WORKFLOW_GITHUB_PR_CAPABILITY_REPO_JONNYTON_WORKFLOW"
    )


def test_capability_env_key_collapses_punctuation():
    # Dots and dashes -> single underscore, uppercased.
    assert _capability_env_key("acme-inc/my.tool-repo") == (
        "WORKFLOW_GITHUB_PR_CAPABILITY_REPO_ACME_INC_MY_TOOL_REPO"
    )


def test_capability_env_key_empty_destination_is_bare_prefix_strip():
    # Empty input produces just the prefix (without trailing _), which
    # cannot collide with any real lookup.
    assert _capability_env_key("") == "WORKFLOW_GITHUB_PR_CAPABILITY_REPO_"


def test_capability_env_keys_distinct_for_two_destinations(monkeypatch):
    monkeypatch.setenv(
        "WORKFLOW_GITHUB_PR_CAPABILITY_REPO_JONNYTON_WORKFLOW", "tok-A"
    )
    monkeypatch.setenv(
        "WORKFLOW_GITHUB_PR_CAPABILITY_REPO_OTHER_OWNER_OTHER_REPO", "tok-B"
    )
    from workflow.effectors.github_pr import _read_capability
    assert _read_capability("Jonnyton/Workflow") == "tok-A"
    assert _read_capability("other-owner/other-repo") == "tok-B"
    assert _read_capability("never-set/repo") == ""


# ---------------------------------------------------------------------------
# Gate 1 — capability env missing
# ---------------------------------------------------------------------------


def test_destination_present_capability_missing_returns_dry_run(universe_dir):
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["phase"] == "phase_2"
    assert result["reason"] == "missing_capability"
    assert result["destination"] == _DESTINATION
    assert result["capability_env_key"] == _CAPABILITY_ENV


def test_capability_token_never_echoed_into_evidence(universe_dir, monkeypatch):
    """The token MUST NOT appear in any returned evidence shape — that's
    the core invariant separating Phase 2 from the Phase-1 self-mintable
    ack."""
    monkeypatch.setenv(_CAPABILITY_ENV, "super-secret-pat-DO-NOT-LEAK")
    # No consent grant -> closes at gate 2; evidence should not include
    # the capability token.
    packet = _make_packet()
    result = run_github_pr_effector(
        node_id="emit",
        output_keys=["pr_packet"],
        run_state={"pr_packet": packet},
        base_path=universe_dir,
        run_id="run-1",
    )
    blob = json.dumps(result)
    assert "super-secret-pat-DO-NOT-LEAK" not in blob, (
        "capability token must NEVER appear in branch-visible evidence"
    )


# ---------------------------------------------------------------------------
# Gate 2 — consent missing
# ---------------------------------------------------------------------------


def test_capability_present_consent_missing_returns_dry_run(
    universe_dir, monkeypatch,
):
    monkeypatch.setenv(_CAPABILITY_ENV, "tok")
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["phase"] == "phase_2"
    assert result["reason"] == "missing_consent"
    assert result["destination"] == _DESTINATION
    # The hint should mention the grant action so the chatbot knows
    # what to surface to the user.
    assert "grant_effector_consent" in result["hint"]


def test_consent_destination_must_match_exactly(universe_dir, monkeypatch):
    """A grant for repo A must NOT authorize writes to repo B."""
    monkeypatch.setenv(_CAPABILITY_ENV, "tok")
    grant_consent(
        universe_dir,
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        destination="some-other/repo",  # different destination
        granted_by="host",
    )
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_not_called()
    assert result["reason"] == "missing_consent"


# ---------------------------------------------------------------------------
# Gate 3 — idempotency dedup
# ---------------------------------------------------------------------------


def test_idempotency_hit_returns_recorded_evidence_no_subprocess(
    universe_dir, monkeypatch,
):
    monkeypatch.setenv(_CAPABILITY_ENV, "tok")
    grant_consent(
        universe_dir,
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        destination=_DESTINATION,
        granted_by="host",
    )
    # Pre-seed a receipt.
    record_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        evidence={
            "pr_url": "https://github.com/Jonnyton/Workflow/pull/901",
            "pr_number": 901,
        },
        run_id="prior-run",
        created_at=1700.0,
    )
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-retry",
        )
    mock_run.assert_not_called()
    assert result["idempotency_dedup_hit"] is True
    assert result["phase"] == "phase_2"
    assert result["evidence"]["pr_number"] == 901
    assert result["recorded_run_id"] == "prior-run"
    assert result["recorded_at"] == 1700.0


def test_idempotency_miss_when_hint_omitted(universe_dir, monkeypatch):
    """A packet without ``idempotency_hint`` is treated as 'always miss'
    so the caller can opt out of dedup. The real-write path then fires."""
    monkeypatch.setenv(_CAPABILITY_ENV, "tok")
    grant_consent(
        universe_dir,
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        destination=_DESTINATION,
        granted_by="host",
    )
    packet = _make_packet(idempotency_hint=None)
    fake = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/Jonnyton/Workflow/pull/777\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_called_once()
    assert result["pr_number"] == 777
    # No receipt should have been recorded (no hint).
    assert lookup_receipt(
        universe_dir,
        idempotency_hint="",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    ) is None


# ---------------------------------------------------------------------------
# Happy path — all three gates open -> real invocation
# ---------------------------------------------------------------------------


def _open_all_gates(universe_dir, monkeypatch):
    monkeypatch.setenv(_CAPABILITY_ENV, "tok")
    grant_consent(
        universe_dir,
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
        destination=_DESTINATION,
        granted_by="host",
    )


def test_all_gates_open_invokes_gh_and_records_receipt(
    universe_dir, monkeypatch,
):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=0,
        stdout=(
            "Creating draft pull request for "
            "auto/loop-2/cycle-001 into main\n"
            "https://github.com/Jonnyton/Workflow/pull/1234\n"
        ),
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_called_once()
    cmd = mock_run.call_args[0][0]
    # Verify the invocation shape — repo + title + base + head + draft + label.
    assert cmd[0] == "gh"
    assert "--repo" in cmd
    assert cmd[cmd.index("--repo") + 1] == _DESTINATION
    assert "--title" in cmd
    assert "--base" in cmd
    assert "--head" in cmd
    assert cmd[cmd.index("--head") + 1] == _HEAD_BRANCH
    assert "--draft" in cmd
    assert "writer:loop-2" in cmd  # label passthrough

    assert result["phase"] == "phase_2"
    assert result["pr_url"] == "https://github.com/Jonnyton/Workflow/pull/1234"
    assert result["pr_number"] == 1234
    assert result["destination"] == _DESTINATION
    assert result["matched_output_key"] == "pr_packet"
    # Capability token must NOT be in the result.
    assert "tok" not in json.dumps(result)

    # Receipt recorded.
    receipt = lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    )
    assert receipt is not None
    assert receipt["run_id"] == "run-1"
    assert receipt["evidence"]["pr_number"] == 1234


def test_second_run_with_same_hint_is_dedup_hit(universe_dir, monkeypatch):
    """Two back-to-back runs with the same idempotency_hint must invoke
    gh exactly once. The second run returns the recorded receipt."""
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/Jonnyton/Workflow/pull/42\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ) as mock_run:
        first = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
        second = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-2-retry",
        )
    assert mock_run.call_count == 1
    assert first["pr_number"] == 42
    assert second["idempotency_dedup_hit"] is True
    assert second["evidence"]["pr_number"] == 42
    assert second["recorded_run_id"] == "run-1"


# ---------------------------------------------------------------------------
# Failure paths — no receipt is recorded on failure
# ---------------------------------------------------------------------------


def test_gh_nonzero_exit_returns_error_and_no_receipt(
    universe_dir, monkeypatch,
):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=2,
        stdout="",
        stderr="gh: GraphQL: Branch already has an open pull request\n",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ):
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-fail",
        )
    assert result["error_kind"] == "gh_nonzero_exit"
    assert "exit 2" in result["error"]
    # No receipt should have been recorded.
    assert lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    ) is None


def test_gh_not_installed_returns_structured_error(universe_dir, monkeypatch):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        side_effect=FileNotFoundError("gh"),
    ):
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    assert result["error_kind"] == "gh_not_installed"


def test_gh_timeout_returns_structured_error(universe_dir, monkeypatch):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        side_effect=subprocess.TimeoutExpired(cmd="gh", timeout=60),
    ):
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    assert result["error_kind"] == "gh_invocation_failed"


def test_gh_returns_zero_but_no_pr_url_returns_error(
    universe_dir, monkeypatch,
):
    """If gh exits 0 but stdout is empty or unparseable, we treat it as a
    nonzero-exit-like failure rather than silently recording a phantom
    receipt with an empty url. Hard rule #8 — fail loudly."""
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    fake = SimpleNamespace(
        returncode=0,
        stdout="ok\n",  # no URL
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ):
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    assert result["error_kind"] == "gh_nonzero_exit"
    # No receipt recorded.
    assert lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    ) is None


# ---------------------------------------------------------------------------
# Branch-level dispatch threads base_path + run_id
# ---------------------------------------------------------------------------


def test_run_effects_for_branch_passes_base_path_and_run_id(
    universe_dir, monkeypatch,
):
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet()
    branch = SimpleNamespace(
        node_defs=[
            NodeDefinition(
                node_id="emit",
                display_name="Emit",
                output_keys=["pr_packet"],
                effects=[EXTERNAL_WRITE_SINK_GITHUB_PR],
            ),
        ],
    )
    fake = SimpleNamespace(
        returncode=0,
        stdout="https://github.com/Jonnyton/Workflow/pull/9\n",
        stderr="",
    )
    with patch(
        "workflow.effectors.github_pr.subprocess.run",
        return_value=fake,
    ):
        ev_map = run_effects_for_branch(
            branch=branch,
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="dispatch-run",
        )
    ev = ev_map["emit"][EXTERNAL_WRITE_SINK_GITHUB_PR]
    assert ev["pr_number"] == 9
    receipt = lookup_receipt(
        universe_dir,
        idempotency_hint="loop-2-cycle-001",
        sink=EXTERNAL_WRITE_SINK_GITHUB_PR,
    )
    assert receipt is not None
    assert receipt["run_id"] == "dispatch-run"


# ---------------------------------------------------------------------------
# Backward compatibility — Phase 1 packets (no destination)
# ---------------------------------------------------------------------------


def test_packet_without_destination_returns_phase_1_evidence(
    universe_dir, monkeypatch,
):
    """A packet that omits the new ``destination`` field is by definition
    a Phase-1 packet. The effector returns the Phase-1 dry-run shape so
    existing consumers don't observe a behavior change."""
    # All gates open at Phase 2, but the packet lacks the destination field.
    _open_all_gates(universe_dir, monkeypatch)
    packet = _make_packet(destination=None)
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=universe_dir,
            run_id="run-1",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["phase"] == "phase_1"
    # Mode reflects the WORKFLOW_EXTERNAL_WRITE_ENABLED env (which is
    # unset here per the autouse fixture).
    assert result["mode"] == "dry_run_default"
    assert result["enabled_explicit"] is False
    assert result["intent"]["sink"] == EXTERNAL_WRITE_SINK_GITHUB_PR


def test_phase_2_dry_run_does_not_carry_phase_1_mode_keys(
    universe_dir, monkeypatch,
):
    """Phase-2 dry-runs (missing capability/consent) must NOT smuggle in
    the Phase-1 ``mode`` / ``enabled_explicit`` keys. Those keys are
    Phase-1-only signals and would confuse consumers that branch on
    them."""
    packet = _make_packet()
    result = run_github_pr_effector(
        node_id="emit",
        output_keys=["pr_packet"],
        run_state={"pr_packet": packet},
        base_path=universe_dir,
        run_id="run-1",
    )
    assert result["phase"] == "phase_2"
    assert "mode" not in result
    assert "enabled_explicit" not in result


# ---------------------------------------------------------------------------
# No base_path -> Phase-2 packets degrade to consent-missing dry-run safely
# ---------------------------------------------------------------------------


def test_phase_2_packet_with_capability_but_no_base_path_is_dry_run(
    monkeypatch,
):
    """If the effector is invoked without a base_path (e.g. by a legacy
    caller), Phase-2-shaped packets still cannot mint a real write.
    Capability env can be read, but consent lookup has nowhere to look,
    so we must fall back to ``missing_consent`` dry-run."""
    monkeypatch.setenv(_CAPABILITY_ENV, "tok")
    packet = _make_packet()
    with patch(
        "workflow.effectors.github_pr.subprocess.run"
    ) as mock_run:
        result = run_github_pr_effector(
            node_id="emit",
            output_keys=["pr_packet"],
            run_state={"pr_packet": packet},
            base_path=None,
            run_id="",
        )
    mock_run.assert_not_called()
    assert result["dry_run"] is True
    assert result["reason"] == "missing_consent"
