#!/usr/bin/env python3
"""Install the committed TinyAssets icon and splash in a generated iOS project.

``mobile/ios`` is generated by ``cap add ios`` and is intentionally not tracked.
Capacitor's template contains placeholder artwork, so every CI build must replace
it after generation.  This installer fails closed if the asset-catalog shape or
pixel sizes drift; a successful archive must never quietly ship Capacitor's icon.
"""

from __future__ import annotations

import json
import shutil
import struct
import sys
from pathlib import Path

MOBILE = Path(__file__).resolve().parents[1]
SOURCE_ICON = MOBILE / "resources" / "icon.png"
SOURCE_SPLASH = MOBILE / "resources" / "splash.png"
ASSET_CATALOG = MOBILE / "ios" / "App" / "App" / "Assets.xcassets"

ICON_FILES = {"AppIcon-512@2x.png"}
SPLASH_FILES = {
    "splash-2732x2732.png",
    "splash-2732x2732-1.png",
    "splash-2732x2732-2.png",
}


def png_size(path: Path) -> tuple[int, int]:
    """Read a PNG's dimensions without adding an image-library dependency."""
    with path.open("rb") as fh:
        head = fh.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n" or head[12:16] != b"IHDR":
        raise ValueError(f"not a PNG: {path}")
    return struct.unpack(">II", head[16:24])


def png_color_type(path: Path) -> int:
    """Return the PNG IHDR color type (Apple app icons must not have alpha)."""
    with path.open("rb") as fh:
        head = fh.read(26)
    if head[:8] != b"\x89PNG\r\n\x1a\n" or head[12:16] != b"IHDR" or len(head) < 26:
        raise ValueError(f"not a PNG: {path}")
    return head[25]


def catalog_filenames(contents_path: Path) -> set[str]:
    try:
        contents = json.loads(contents_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read asset catalog {contents_path}: {exc}") from exc
    return {
        image["filename"]
        for image in contents.get("images", [])
        if isinstance(image, dict) and image.get("filename")
    }


def install_assets(
    asset_catalog: Path = ASSET_CATALOG,
    source_icon: Path = SOURCE_ICON,
    source_splash: Path = SOURCE_SPLASH,
) -> int:
    expected_sources = ((source_icon, (1024, 1024)), (source_splash, (2732, 2732)))
    problems: list[str] = []
    for source, expected_size in expected_sources:
        if not source.is_file():
            problems.append(f"missing source asset: {source}")
            continue
        try:
            actual_size = png_size(source)
        except ValueError as exc:
            problems.append(str(exc))
            continue
        if actual_size != expected_size:
            problems.append(f"{source} is {actual_size}, expected {expected_size}")
        try:
            color_type = png_color_type(source)
        except ValueError as exc:
            problems.append(str(exc))
            continue
        if color_type != 2:
            problems.append(
                f"{source} has PNG color type {color_type}, expected RGB color type 2 "
                "without alpha"
            )

    catalogs = (
        (asset_catalog / "AppIcon.appiconset", ICON_FILES, source_icon, (1024, 1024)),
        (asset_catalog / "Splash.imageset", SPLASH_FILES, source_splash, (2732, 2732)),
    )
    for directory, expected_files, _source, expected_size in catalogs:
        contents_path = directory / "Contents.json"
        try:
            found_files = catalog_filenames(contents_path)
        except ValueError as exc:
            problems.append(str(exc))
            continue
        if found_files != expected_files:
            problems.append(
                f"{contents_path} references {sorted(found_files)}, "
                f"expected {sorted(expected_files)}; Capacitor's template changed"
            )
            continue
        for filename in expected_files:
            target = directory / filename
            if not target.is_file():
                problems.append(f"asset catalog references missing file: {target}")
                continue
            try:
                actual_size = png_size(target)
            except ValueError as exc:
                problems.append(str(exc))
                continue
            if actual_size != expected_size:
                problems.append(f"{target} is {actual_size}, expected {expected_size}")

    if problems:
        print("error: iOS asset install aborted:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    for directory, expected_files, source, _expected_size in catalogs:
        for filename in expected_files:
            shutil.copyfile(source, directory / filename)

    print("installed TinyAssets iOS icon + splash (4 catalog images)")
    return 0


def main() -> int:
    if not ASSET_CATALOG.is_dir():
        print(
            f"error: {ASSET_CATALOG} missing — run `npx cap add ios` first",
            file=sys.stderr,
        )
        return 1
    return install_assets()


if __name__ == "__main__":
    sys.exit(main())
