package io.tinyassets.app;

import android.content.Intent;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.charset.StandardCharsets;

/**
 * Loopback OAuth catcher: the one piece a phone needs to complete the same
 * browser sign-in a desktop CLI does. The app opens the provider's authorize
 * page in an in-app tab with redirect_uri http://localhost:PORT/auth/callback;
 * Chrome resolves localhost to this device, this tiny listener answers the
 * redirect, hands the URL (code + state) to the web layer, and brings the app
 * back to the front. Loopback-only bind, one flow at a time, closed on stop.
 *
 * Installed into the generated Android project by mobile/scripts/add_app_scheme.py
 * (android/ is regenerated by `cap add android`, so it cannot be committed).
 */
@CapacitorPlugin(name = "LocalCallback")
public class LocalCallbackPlugin extends Plugin {
    private ServerSocket server;
    private String expectedPath = "/auth/callback";

    @PluginMethod
    public void start(PluginCall call) {
        int port = call.getInt("port", 1455);
        String path = call.getString("path", "/auth/callback");
        expectedPath = path;
        stopServer();
        try {
            ServerSocket s = new ServerSocket();
            s.setReuseAddress(true);
            s.bind(new InetSocketAddress(InetAddress.getLoopbackAddress(), port), 4);
            server = s;
        } catch (IOException e) {
            call.reject("bind failed: " + e.getMessage());
            return;
        }
        final ServerSocket s = server;
        Thread t = new Thread(() -> {
            while (!s.isClosed()) {
                try (Socket c = s.accept()) {
                    handle(c);
                } catch (IOException e) {
                    break;
                }
            }
        }, "tinyassets-local-callback");
        t.setDaemon(true);
        t.start();
        JSObject r = new JSObject();
        r.put("port", port);
        call.resolve(r);
    }

    @PluginMethod
    public void stop(PluginCall call) {
        stopServer();
        call.resolve();
    }

    private void handle(Socket c) throws IOException {
        c.setSoTimeout(5000);
        BufferedReader in = new BufferedReader(new InputStreamReader(c.getInputStream(), StandardCharsets.UTF_8));
        String request = in.readLine();
        String target = "/";
        if (request != null) {
            String[] parts = request.split(" ");
            if (parts.length >= 2) target = parts[1];
        }
        String header;
        while ((header = in.readLine()) != null && !header.isEmpty()) { /* drain */ }

        boolean isCallback = target.startsWith(expectedPath);
        String body = isCallback
            ? "<!doctype html><html><head><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
              + "<meta http-equiv=\"refresh\" content=\"1;url=intent://auth#Intent;scheme=tinyassets;package=io.tinyassets.app;end\"></head>"
              + "<body style=\"font-family:system-ui;background:#0f1020;color:#eef0ff;text-align:center;padding:3rem\">"
              + "<p>Signed in. Returning you to TinyAssets&hellip;</p>"
              + "<p><a style=\"color:#6c7bf2\" href=\"intent://auth#Intent;scheme=tinyassets;package=io.tinyassets.app;end\">Open TinyAssets</a></p>"
              + "</body></html>"
            : "<!doctype html><html><body></body></html>";
        byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
        OutputStream out = c.getOutputStream();
        out.write((
            (isCallback ? "HTTP/1.1 200 OK" : "HTTP/1.1 404 Not Found")
            + "\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: " + bytes.length
            + "\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n").getBytes(StandardCharsets.UTF_8));
        out.write(bytes);
        out.flush();
        if (!isCallback) return;

        JSObject ev = new JSObject();
        ev.put("url", "http://localhost" + target);
        notifyListeners("callback", ev, true);
        bringToFront();
        stopServer();   // one flow per start(): the listener closes after the first callback
    }

    private void bringToFront() {
        try {
            Intent i = new Intent(getContext(), getActivity().getClass());
            i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);
            getContext().startActivity(i);
        } catch (Exception ignored) {
            // The served page's intent:// refresh + link are the fallback.
        }
    }

    private void stopServer() {
        ServerSocket s = server;
        server = null;
        if (s != null) {
            try { s.close(); } catch (IOException ignored) { }
        }
    }

    @Override
    protected void handleOnDestroy() {
        stopServer();
    }
}
