package io.tinyassets.app;

import android.content.Intent;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.charset.StandardCharsets;

/**
 * Loopback OAuth catcher: the one piece a phone needs to complete the same
 * browser sign-in a desktop CLI does. The app opens the provider's authorize
 * page in an in-app tab with redirect_uri http://localhost:PORT/auth/callback;
 * Chrome resolves localhost to this device, this tiny listener answers the
 * redirect, hands the URL (code + state) to the web layer, and brings the app
 * back to the front. Loopback-only bind (v4 + v6), one flow at a time.
 *
 * Installed into the generated Android project by mobile/scripts/add_app_scheme.py
 * (android/ is regenerated by `cap add android`, so it cannot be committed).
 */
@CapacitorPlugin(name = "LocalCallback")
public class LocalCallbackPlugin extends Plugin {
    private static final int MAX_REQUEST_BYTES = 8192;   // a callback line + a few headers
    private static final int SOCKET_TIMEOUT_MS = 3000;

    // Keep serving the callback page for a while after the valid callback so
    // a reload of the tab (or a slow hand-off) still lands on it, not on a
    // connection-refused page.
    private static final long LINGER_MS = 3 * 60 * 1000L;

    private ServerSocket server4;
    private ServerSocket server6;
    private volatile String expectedPath = "/auth/callback";
    private volatile String expectedState = "";
    // Accepted exactly once per start() across both listeners; afterwards only
    // an identical request (a reload of the same callback URL) is re-served.
    private final java.util.concurrent.atomic.AtomicReference<String> accepted =
        new java.util.concurrent.atomic.AtomicReference<>(null);
    // Generation token: a linger thread from an older start() must never close
    // a newer listener.
    private final java.util.concurrent.atomic.AtomicInteger generation =
        new java.util.concurrent.atomic.AtomicInteger(0);

    @PluginMethod
    public void start(PluginCall call) {
        int port = call.getInt("port", 1455);
        String path = call.getString("path", "/auth/callback");
        String state = call.getString("state", "");
        if (state == null || state.isEmpty()) {
            call.reject("state is required");
            return;
        }
        expectedPath = path;
        expectedState = state;
        accepted.set(null);
        generation.incrementAndGet();
        stopServer();
        // Chrome may resolve "localhost" to ::1 before 127.0.0.1; listen on
        // BOTH loopbacks so the redirect never waits on a dead address. IPv6
        // is best-effort (some devices have no ::1).
        try {
            server4 = bind(InetAddress.getByName("127.0.0.1"), port);
        } catch (IOException e) {
            call.reject("bind failed: " + e.getMessage());
            return;
        }
        try {
            server6 = bind(InetAddress.getByName("::1"), port);
        } catch (IOException ignored) {
            server6 = null;
        }
        serve(server4);
        if (server6 != null) serve(server6);
        JSObject r = new JSObject();
        r.put("port", port);
        r.put("ipv6", server6 != null);
        call.resolve(r);
    }

    private static ServerSocket bind(InetAddress addr, int port) throws IOException {
        ServerSocket s = new ServerSocket();
        s.setReuseAddress(true);
        s.bind(new InetSocketAddress(addr, port), 4);
        return s;
    }

    private void serve(final ServerSocket s) {
        Thread t = new Thread(() -> {
            while (!s.isClosed()) {
                Socket c;
                try {
                    c = s.accept();
                } catch (IOException e) {
                    break;   // the server socket closed (stop/destroy/linger end)
                }
                // A misbehaving client (silent connect, slow headers, timeout)
                // must never end the accept loop - that would let any local
                // process preempt the real callback by connecting first. And
                // nothing on this thread may ever bring the app down.
                try {
                    handle(c);
                } catch (Throwable ignored) {
                } finally {
                    try { c.close(); } catch (IOException ignored) { }
                }
            }
        }, "tinyassets-local-callback");
        t.setDaemon(true);
        t.start();
    }

    @PluginMethod
    public void stop(PluginCall call) {
        stopServer();
        call.resolve();
    }

    /**
     * Any app on the phone can open http://localhost:PORT, so nothing a client
     * sends is trusted: the request is read with a hard byte cap (no unbounded
     * line reads), only an exact GET of the expected path carrying EXACTLY the
     * expected state is accepted, and anything else gets a 404 and is ignored
     * without closing the listener - a stranger cannot preempt the real
     * callback by connecting first. The listener closes only after the valid
     * callback has been handed to the web layer.
     */
    private void handle(Socket c) throws IOException {
        c.setSoTimeout(SOCKET_TIMEOUT_MS);
        // Only the request line matters; read it with a hard cap and stop at
        // the first CRLF so header size (Chrome sends plenty) is irrelevant.
        byte[] buf = new byte[MAX_REQUEST_BYTES];
        int n = 0;
        java.io.InputStream in = c.getInputStream();
        while (n < buf.length) {
            int r = in.read(buf, n, buf.length - n);
            if (r < 0) break;
            n += r;
            if (indexOfCrlf(buf, n) >= 0) break;
        }
        String head = new String(buf, 0, n, StandardCharsets.ISO_8859_1);
        int eol = head.indexOf("\r\n");
        String requestLine = eol >= 0 ? head.substring(0, eol) : head;
        String[] parts = requestLine.split(" ");
        String target = (parts.length >= 2 && "GET".equals(parts[0])) ? parts[1] : "";

        // Exactly one acceptance per start(), atomically across the v4 and v6
        // listeners. After that, ONLY a byte-identical request (the tab
        // reloading the same callback URL) gets the page again; any other
        // local client asking for the path learns nothing and triggers
        // nothing.
        boolean first = false;
        if (isExpectedCallback(target)) {
            first = accepted.compareAndSet(null, target);
        }
        boolean replay = !first && target.length() > 0 && target.equals(accepted.get());
        String page = (first || replay) ? target : null;
        String body = page != null ? callbackPage(page) : "<!doctype html><html><body></body></html>";
        byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
        OutputStream out = c.getOutputStream();
        out.write((
            (page != null ? "HTTP/1.1 200 OK" : "HTTP/1.1 404 Not Found")
            + "\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: " + bytes.length
            + "\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n").getBytes(StandardCharsets.UTF_8));
        out.write(bytes);
        out.flush();
        if (!first) return;   // ignored or replayed; the web layer is notified once

        JSObject ev = new JSObject();
        ev.put("url", "http://localhost" + target);
        notifyListeners("callback", ev, true);
        bringToFront();
        scheduleLingerStop(generation.get());
    }

    /**
     * The page the in-app tab lands on. It carries the callback's own query
     * (code + state) into the app through the package-qualified deep link, so
     * the app completes the link even if the listener event never reached the
     * web layer or the app could not bring itself forward: auto-attempt after
     * a moment, and a big tap target (a user gesture always launches the app).
     */
    private static String callbackPage(String target) {
        int q = target.indexOf('?');
        String query = q >= 0 ? target.substring(q + 1) : "";
        // Rebuild the deep link from an allowlist of fields, re-encoded: the
        // raw query never flows into the page or the intent.
        StringBuilder rebuilt = new StringBuilder("provider=openai");
        for (String kv : query.split("&")) {
            int eq = kv.indexOf('=');
            String k = eq >= 0 ? kv.substring(0, eq) : kv;
            String v = eq >= 0 ? kv.substring(eq + 1) : "";
            if (!(k.equals("code") || k.equals("state") || k.equals("error") || k.equals("error_description"))) continue;
            try {
                v = java.net.URLDecoder.decode(v, "UTF-8");
                rebuilt.append('&').append(k).append('=').append(java.net.URLEncoder.encode(v, "UTF-8"));
            } catch (Exception ignored) { }
        }
        String deep = "intent://auth?" + htmlEscape(rebuilt.toString())
            + "#Intent;scheme=tinyassets;package=io.tinyassets.app;end";
        return "<!doctype html><html><head><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
            + "<meta http-equiv=\"refresh\" content=\"1;url=" + deep + "\"></head>"
            + "<body style=\"font-family:system-ui;background:#0f1020;color:#eef0ff;text-align:center;padding:3rem 1.5rem\">"
            + "<p style=\"font-size:1.15rem\">Signed in with OpenAI.</p>"
            + "<p><a style=\"display:inline-block;background:#6c7bf2;color:#fff;text-decoration:none;font-weight:600;padding:.9rem 1.4rem;border-radius:12px;font-size:1.1rem\" href=\"" + deep + "\">Open TinyAssets</a></p>"
            + "<p style=\"color:#a6a9c8;font-size:.9rem\">Tap the button if you are not taken back automatically.</p>"
            + "</body></html>";
    }

    private static String htmlEscape(String s) {
        return s.replace("&", "&amp;").replace("\"", "&quot;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private void scheduleLingerStop(final int gen) {
        Thread t = new Thread(() -> {
            try { Thread.sleep(LINGER_MS); } catch (InterruptedException ignored) { }
            // Only close the listener this linger belongs to; a newer start()
            // (higher generation) owns fresh sockets and must stay up.
            if (generation.get() == gen) stopServer();
        }, "tinyassets-local-callback-linger");
        t.setDaemon(true);
        t.start();
    }

    private static int indexOfCrlf(byte[] b, int len) {
        for (int i = 0; i + 1 < len; i++) {
            if (b[i] == '\r' && b[i + 1] == '\n') return i;
        }
        return -1;
    }

    /**
     * Exact path, and a query whose `state` equals the one this flow started
     * with, carrying either a `code` (success) or an `error` (the user denied,
     * or OpenAI refused) - both must reach the web layer so it can finish the
     * flow instead of leaving the user on a blank page until timeout.
     */
    private boolean isExpectedCallback(String target) {
        if (target == null || target.isEmpty()) return false;
        int q = target.indexOf('?');
        String path = q >= 0 ? target.substring(0, q) : target;
        if (!path.equals(expectedPath)) return false;
        if (q < 0) return false;
        String query = target.substring(q + 1);
        int hash = query.indexOf('#');
        if (hash >= 0) query = query.substring(0, hash);
        boolean stateOk = false, hasOutcome = false;
        for (String kv : query.split("&")) {
            int eq = kv.indexOf('=');
            String k = eq >= 0 ? kv.substring(0, eq) : kv;
            String v = eq >= 0 ? kv.substring(eq + 1) : "";
            try { v = java.net.URLDecoder.decode(v, "UTF-8"); } catch (Exception e) { return false; }
            if (k.equals("state")) stateOk = v.equals(expectedState);
            if ((k.equals("code") || k.equals("error")) && !v.isEmpty()) hasOutcome = true;
        }
        return stateOk && hasOutcome;
    }

    private void bringToFront() {
        try {
            final android.app.Activity activity = getActivity();
            if (activity == null) return;
            activity.runOnUiThread(() -> {
                try {
                    Intent i = new Intent(activity, activity.getClass());
                    i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);
                    activity.startActivity(i);
                } catch (Throwable ignored) {
                    // Background-launch restrictions: the served page's deep
                    // link (auto + button) is the fallback.
                }
            });
        } catch (Throwable ignored) { }
    }

    private void stopServer() {
        ServerSocket a = server4, b = server6;
        server4 = null;
        server6 = null;
        if (a != null) { try { a.close(); } catch (IOException ignored) { } }
        if (b != null) { try { b.close(); } catch (IOException ignored) { } }
    }

    @Override
    protected void handleOnDestroy() {
        stopServer();
    }
}
